version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - errchkjson
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    errorlint:
      errorf: false
      asserts: true
      comparison: true
    revive:
      confidence: 0.8
      severity: error
      rules:
        - name: blank-imports
          disabled: true
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
          disabled: true
        - name: increment-decrement
        - name: var-naming
          disabled: true
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
          disabled: true
        - name: indent-error-flow
          disabled: true
        - name: errorf
        - name: empty-block
          disabled: true
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
