model:
  filename: ./pkg/scraper/stashbox/graphql/models_gen.go
client:
  filename: ./pkg/scraper/stashbox/graphql/client.go
models:
  Date:
    model: github.com/99designs/gqlgen/graphql.String
endpoint:
  url: https://stashdb.org/graphql
query:  
   - "./graphql/stash-box/*.graphql"
