package scraper

import (
	"strings"

	"github.com/stashapp/stash/pkg/logger"
)

func countryDict(name string) *string {
	countryNameMapping := map[string]string{
		"Afghanistan":                          "AF",
		"Albania":                              "AL",
		"Algeria":                              "DZ",
		"America":                              "US",
		"American":                             "US",
		"American Samoa":                       "AS",
		"Andorra":                              "AD",
		"Angola":                               "AO",
		"Anguilla":                             "AI",
		"Antarctica":                           "AQ",
		"Antigua and Barbuda":                  "AG",
		"Argentina":                            "AR",
		"Armenia":                              "AM",
		"Aruba":                                "AW",
		"Australia":                            "AU",
		"Austria":                              "AT",
		"Azerbaijan":                           "AZ",
		"Bahamas":                              "BS",
		"Bahrain":                              "BH",
		"Bangladesh":                           "BD",
		"Barbados":                             "BB",
		"Belarus":                              "BY",
		"Belgium":                              "BE",
		"Belize":                               "BZ",
		"Benin":                                "BJ",
		"Bermuda":                              "BM",
		"Bhutan":                               "BT",
		"Bolivia":                              "BO",
		"Bosnia and Herzegovina":               "BA",
		"Botswana":                             "BW",
		"Bouvet Island":                        "BV",
		"Brazil":                               "BR",
		"British Indian Ocean Territory":       "IO",
		"Brunei Darussalam":                    "BN",
		"Bulgaria":                             "BG",
		"Burkina Faso":                         "BF",
		"Burundi":                              "BI",
		"Cambodia":                             "KH",
		"Cameroon":                             "CM",
		"Canada":                               "CA",
		"Cape Verde":                           "CV",
		"Cayman Islands":                       "KY",
		"Central African Republic":             "CF",
		"Chad":                                 "TD",
		"Chile":                                "CL",
		"China":                                "CN",
		"Christmas Island":                     "CX",
		"Cocos (Keeling) Islands":              "CC",
		"Colombia":                             "CO",
		"Comoros":                              "KM",
		"Congo":                                "CG",
		"Congo the Democratic Republic of the": "CD",
		"Cook Islands":                         "CK",
		"Costa Rica":                           "CR",
		"Cote D'Ivoire":                        "CI",
		"Croatia":                              "HR",
		"Cuba":                                 "CU",
		"Cyprus":                               "CY",
		"Czech Republic":                       "CZ",
		"Czechia":                              "CZ",
		"Denmark":                              "DK",
		"Djibouti":                             "DJ",
		"Dominica":                             "DM",
		"Dominican Republic":                   "DO",
		"Ecuador":                              "EC",
		"Egypt":                                "EG",
		"El Salvador":                          "SV",
		"Equatorial Guinea":                    "GQ",
		"Eritrea":                              "ER",
		"Estonia":                              "EE",
		"Ethiopia":                             "ET",
		"Falkland Islands (Malvinas)":          "FK",
		"Faroe Islands":                        "FO",
		"Fiji":                                 "FJ",
		"Finland":                              "FI",
		"France":                               "FR",
		"French Guiana":                        "GF",
		"French Polynesia":                     "PF",
		"French Southern Territories":          "TF",
		"Gabon":                                "GA",
		"Gambia":                               "GM",
		"Georgia":                              "GE",
		"Germany":                              "DE",
		"Ghana":                                "GH",
		"Gibraltar":                            "GI",
		"Greece":                               "GR",
		"Greenland":                            "GL",
		"Grenada":                              "GD",
		"Guadeloupe":                           "GP",
		"Guam":                                 "GU",
		"Guatemala":                            "GT",
		"Guinea":                               "GN",
		"Guinea-Bissau":                        "GW",
		"Guyana":                               "GY",
		"Haiti":                                "HT",
		"Heard Island and McDonald Islands":    "HM",
		"Holy See (Vatican City State)":        "VA",
		"Honduras":                             "HN",
		"Hong Kong":                            "HK",
		"Hungary":                              "HU",
		"Iceland":                              "IS",
		"India":                                "IN",
		"Indonesia":                            "ID",
		"Iran":                                 "IR",
		"Iran Islamic Republic of":             "IR",
		"Iraq":                                 "IQ",
		"Ireland":                              "IE",
		"Israel":                               "IL",
		"Italy":                                "IT",
		"Jamaica":                              "JM",
		"Japan":                                "JP",
		"Jordan":                               "JO",
		"Kazakhstan":                           "KZ",
		"Kenya":                                "KE",
		"Kiribati":                             "KI",
		"North Korea":                          "KP",
		"South Korea":                          "KR",
		"Kuwait":                               "KW",
		"Kyrgyzstan":                           "KG",
		"Lao People's Democratic Republic":     "LA",
		"Latvia":                               "LV",
		"Lebanon":                              "LB",
		"Lesotho":                              "LS",
		"Liberia":                              "LR",
		"Libya":                                "LY",
		"Liechtenstein":                        "LI",
		"Lithuania":                            "LT",
		"Luxembourg":                           "LU",
		"Macao":                                "MO",
		"Madagascar":                           "MG",
		"Malawi":                               "MW",
		"Malaysia":                             "MY",
		"Maldives":                             "MV",
		"Mali":                                 "ML",
		"Malta":                                "MT",
		"Marshall Islands":                     "MH",
		"Martinique":                           "MQ",
		"Mauritania":                           "MR",
		"Mauritius":                            "MU",
		"Mayotte":                              "YT",
		"Mexico":                               "MX",
		"Micronesia Federated States of":       "FM",
		"Moldova":                              "MD",
		"Moldova Republic of":                  "MD",
		"Moldova, Republic of":                 "MD",
		"Monaco":                               "MC",
		"Mongolia":                             "MN",
		"Montserrat":                           "MS",
		"Morocco":                              "MA",
		"Mozambique":                           "MZ",
		"Myanmar":                              "MM",
		"Namibia":                              "NA",
		"Nauru":                                "NR",
		"Nepal":                                "NP",
		"Netherlands":                          "NL",
		"New Caledonia":                        "NC",
		"New Zealand":                          "NZ",
		"Nicaragua":                            "NI",
		"Niger":                                "NE",
		"Nigeria":                              "NG",
		"Niue":                                 "NU",
		"Norfolk Island":                       "NF",
		"North Macedonia Republic of":          "MK",
		"Northern Mariana Islands":             "MP",
		"Norway":                               "NO",
		"Oman":                                 "OM",
		"Pakistan":                             "PK",
		"Palau":                                "PW",
		"Palestinian Territory Occupied":       "PS",
		"Panama":                               "PA",
		"Papua New Guinea":                     "PG",
		"Paraguay":                             "PY",
		"Peru":                                 "PE",
		"Philippines":                          "PH",
		"Pitcairn":                             "PN",
		"Poland":                               "PL",
		"Portugal":                             "PT",
		"Puerto Rico":                          "PR",
		"Qatar":                                "QA",
		"Reunion":                              "RE",
		"Romania":                              "RO",
		"Russia":                               "RU",
		"Russian Federation":                   "RU",
		"Rwanda":                               "RW",
		"Saint Helena":                         "SH",
		"Saint Kitts and Nevis":                "KN",
		"Saint Lucia":                          "LC",
		"Saint Pierre and Miquelon":            "PM",
		"Saint Vincent and the Grenadines":     "VC",
		"Samoa":                                "WS",
		"San Marino":                           "SM",
		"Sao Tome and Principe":                "ST",
		"Saudi Arabia":                         "SA",
		"Senegal":                              "SN",
		"Seychelles":                           "SC",
		"Sierra Leone":                         "SL",
		"Singapore":                            "SG",
		"Slovakia":                             "SK",
		"Slovak Republic":                      "SK",
		"Slovenia":                             "SI",
		"Solomon Islands":                      "SB",
		"Somalia":                              "SO",
		"South Africa":                         "ZA",
		"South Georgia and the South Sandwich Islands": "GS",
		"Spain":                                "ES",
		"Sri Lanka":                            "LK",
		"Sudan":                                "SD",
		"Suriname":                             "SR",
		"Svalbard and Jan Mayen":               "SJ",
		"Eswatini":                             "SZ",
		"Sweden":                               "SE",
		"Switzerland":                          "CH",
		"Syrian Arab Republic":                 "SY",
		"Taiwan":                               "TW",
		"Tajikistan":                           "TJ",
		"Tanzania United Republic of":          "TZ",
		"Thailand":                             "TH",
		"Timor-Leste":                          "TL",
		"Togo":                                 "TG",
		"Tokelau":                              "TK",
		"Tonga":                                "TO",
		"Trinidad and Tobago":                  "TT",
		"Tunisia":                              "TN",
		"Turkey":                               "TR",
		"Turkmenistan":                         "TM",
		"Turks and Caicos Islands":             "TC",
		"Tuvalu":                               "TV",
		"Uganda":                               "UG",
		"Ukraine":                              "UA",
		"United Arab Emirates":                 "AE",
		"England":                              "GB",
		"Great Britain":                        "GB",
		"United Kingdom":                       "GB",
		"USA":                                  "US",
		"United States":                        "US",
		"United States of America":             "US",
		"United States Minor Outlying Islands": "UM",
		"Uruguay":                              "UY",
		"Uzbekistan":                           "UZ",
		"Vanuatu":                              "VU",
		"Venezuela":                            "VE",
		"Vietnam":                              "VN",
		"Virgin Islands British":               "VG",
		"Virgin Islands U.S.":                  "VI",
		"Wallis and Futuna":                    "WF",
		"Western Sahara":                       "EH",
		"Yemen":                                "YE",
		"Zambia":                               "ZM",
		"Zimbabwe":                             "ZW",
		"Åland Islands":                        "AX",
		"Bonaire Sint Eustatius and Saba":      "BQ",
		"Curaçao":                              "CW",
		"Guernsey":                             "GG",
		"Isle of Man":                          "IM",
		"Jersey":                               "JE",
		"Montenegro":                           "ME",
		"Saint Barthélemy":                     "BL",
		"Saint Martin (French part)":           "MF",
		"Serbia":                               "RS",
		"Sint Maarten (Dutch part)":            "SX",
		"South Sudan":                          "SS",
		"Kosovo":                               "XK",
	}

	v, exists := countryNameMapping[name]
	if exists {
		return &v
	}

	return nil
}

func resolveCountryName(name *string) *string {
	if name == nil {
		return nil
	}

	trimmedName := strings.TrimSpace(*name)
	if len(trimmedName) == 2 {
		// If name is two characters it's likely already an ISO value
		return &trimmedName
	} else if len(trimmedName) == 0 {
		return nil
	}

	res := countryDict(trimmedName)
	if res == nil {
		logger.Infof("Scraped country was not recognized: %s", trimmedName)
	}

	return res
}
