fragment AudioData on Audio {
  id
  title
  code
  details
  urls
  date
  rating100
  o_counter
  organized
  created_at
  updated_at
  resume_time
  last_played_at
  play_duration
  play_count

  play_history
  o_history

  files {
    ...AudioFileData
  }

  paths {
    screenshot
    stream
  }

  galleries {
    ...SlimGalleryData
  }

  studio {
    ...SlimStudioData
  }

  groups {
    group {
      ...GroupData
    }
    audio_index
  }

  tags {
    ...SlimTagData
  }

  performers {
    ...PerformerData
  }

  audioStreams {
    url
    mime_type
    label
  }

  custom_fields
}

fragment SelectAudioData on Audio {
  id
  title
  date
  code
  studio {
    name
  }
  files {
    path
  }
}
