"The query root for this schema"
type Query {
  # Filters
  findSavedFilter(id: ID!): SavedFilter
  findSavedFilters(mode: FilterMode): [SavedFilter!]!
  findDefaultFilter(mode: FilterMode!): SavedFilter
    @deprecated(reason: "default filter now stored in UI config")

  "Find a file by its id or path"
  findFile(id: ID, path: String): BaseFile!

  "Queries for Files"
  findFiles(
    file_filter: FileFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindFilesResultType!

  "Find a file by its id or path"
  findFolder(id: ID, path: String): Folder!

  "Queries for Files"
  findFolders(
    folder_filter: FolderFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindFoldersResultType!

  "Find a scene by ID or Checksum"
  findScene(id: ID, checksum: String): Scene
  findSceneByHash(input: SceneHashInput!): Scene

  "A function which queries Scene objects"
  findScenes(
    scene_filter: SceneFilterType
    scene_ids: [Int!] @deprecated(reason: "use ids")
    ids: [ID!]
    filter: FindFilterType
  ): FindScenesResultType!

  findScenesByPathRegex(filter: FindFilterType): FindScenesResultType!

  """
  Returns any groups of scenes that are perceptual duplicates within the queried distance
  and the difference between their duration is smaller than durationDiff
  """
  findDuplicateScenes(
    distance: Int
    """
    Max difference in seconds between files in order to be considered for similarity matching.
    Fractional seconds are ok: 0.5 will mean only files that have durations within 0.5 seconds between them will be matched based on PHash distance.
    """
    duration_diff: Float
  ): [[Scene!]!]!

  "Return valid stream paths"
  sceneStreams(id: ID): [SceneStreamEndpoint!]!

  parseSceneFilenames(
    filter: FindFilterType
    config: SceneParserInput!
  ): SceneParserResultType!

  "A function which queries SceneMarker objects"
  findSceneMarkers(
    scene_marker_filter: SceneMarkerFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindSceneMarkersResultType!

  findImage(id: ID, checksum: String): Image

  "A function which queries Scene objects"
  findImages(
    image_filter: ImageFilterType
    image_ids: [Int!] @deprecated(reason: "use ids")
    ids: [ID!]
    filter: FindFilterType
  ): FindImagesResultType!

  "Find a performer by ID"
  findPerformer(id: ID!): Performer
  "A function which queries Performer objects"
  findPerformers(
    performer_filter: PerformerFilterType
    filter: FindFilterType
    performer_ids: [Int!] @deprecated(reason: "use ids")
    ids: [ID!]
  ): FindPerformersResultType!

  "Find a studio by ID"
  findStudio(id: ID!): Studio
  "A function which queries Studio objects"
  findStudios(
    studio_filter: StudioFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindStudiosResultType!

  "Find a movie by ID"
  findMovie(id: ID!): Movie @deprecated(reason: "Use findGroup instead")
  "A function which queries Movie objects"
  findMovies(
    movie_filter: MovieFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindMoviesResultType! @deprecated(reason: "Use findGroups instead")

  "Find a group by ID"
  findGroup(id: ID!): Group
  "A function which queries Group objects"
  findGroups(
    group_filter: GroupFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindGroupsResultType!

  findGallery(id: ID!): Gallery
  findGalleries(
    gallery_filter: GalleryFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindGalleriesResultType!

  findTag(id: ID!): Tag
  findTags(
    tag_filter: TagFilterType
    filter: FindFilterType
    ids: [ID!]
  ): FindTagsResultType!

  "Retrieve random scene markers for the wall"
  markerWall(q: String): [SceneMarker!]!
  "Retrieve random scenes for the wall"
  sceneWall(q: String): [Scene!]!

  "Get marker strings"
  markerStrings(q: String, sort: String): [MarkerStringsResultType]!
  "Get stats"
  stats: StatsResultType!
  "Organize scene markers by tag for a given scene ID"
  sceneMarkerTags(scene_id: ID!): [SceneMarkerTag!]!

  logs: [LogEntry!]!

  # Scrapers

  "List available scrapers"
  listScrapers(types: [ScrapeContentType!]!): [Scraper!]!

  "Scrape for a single scene"
  scrapeSingleScene(
    source: ScraperSourceInput!
    input: ScrapeSingleSceneInput!
  ): [ScrapedScene!]!
  "Scrape for multiple scenes"
  scrapeMultiScenes(
    source: ScraperSourceInput!
    input: ScrapeMultiScenesInput!
  ): [[ScrapedScene!]!]!

  "Scrape for a single studio"
  scrapeSingleStudio(
    source: ScraperSourceInput!
    input: ScrapeSingleStudioInput!
  ): [ScrapedStudio!]!

  "Scrape for a single tag"
  scrapeSingleTag(
    source: ScraperSourceInput!
    input: ScrapeSingleTagInput!
  ): [ScrapedTag!]!

  "Scrape for a single performer"
  scrapeSinglePerformer(
    source: ScraperSourceInput!
    input: ScrapeSinglePerformerInput!
  ): [ScrapedPerformer!]!
  "Scrape for multiple performers"
  scrapeMultiPerformers(
    source: ScraperSourceInput!
    input: ScrapeMultiPerformersInput!
  ): [[ScrapedPerformer!]!]!

  "Scrape for a single gallery"
  scrapeSingleGallery(
    source: ScraperSourceInput!
    input: ScrapeSingleGalleryInput!
  ): [ScrapedGallery!]!

  "Scrape for a single movie"
  scrapeSingleMovie(
    source: ScraperSourceInput!
    input: ScrapeSingleMovieInput!
  ): [ScrapedMovie!]! @deprecated(reason: "Use scrapeSingleGroup instead")

  "Scrape for a single group"
  scrapeSingleGroup(
    source: ScraperSourceInput!
    input: ScrapeSingleGroupInput!
  ): [ScrapedGroup!]!

  "Scrape for a single image"
  scrapeSingleImage(
    source: ScraperSourceInput!
    input: ScrapeSingleImageInput!
  ): [ScrapedImage!]!

  "Scrapes content based on a URL"
  scrapeURL(url: String!, ty: ScrapeContentType!): ScrapedContent

  "Scrapes a complete performer record based on a URL"
  scrapePerformerURL(url: String!): ScrapedPerformer
  "Scrapes a complete scene record based on a URL"
  scrapeSceneURL(url: String!): ScrapedScene
  "Scrapes a complete gallery record based on a URL"
  scrapeGalleryURL(url: String!): ScrapedGallery
  "Scrapes a complete image record based on a URL"
  scrapeImageURL(url: String!): ScrapedImage
  "Scrapes a complete movie record based on a URL"
  scrapeMovieURL(url: String!): ScrapedMovie
    @deprecated(reason: "Use scrapeGroupURL instead")
  "Scrapes a complete group record based on a URL"
  scrapeGroupURL(url: String!): ScrapedGroup

  # Plugins
  "List loaded plugins"
  plugins: [Plugin!]
  "List available plugin operations"
  pluginTasks: [PluginTask!]

  # Packages
  "List installed packages"
  installedPackages(type: PackageType!): [Package!]!
  "List available packages"
  availablePackages(type: PackageType!, source: String!): [Package!]!

  # Config
  "Returns the current, complete configuration"
  configuration: ConfigResult!
  "Returns an array of paths for the given path"
  directory(
    "The directory path to list"
    path: String
    "Desired collation locale. Determines the order of the directory result. eg. 'en-US', 'pt-BR', ..."
    locale: String = "en"
  ): Directory!
  validateStashBoxCredentials(input: StashBoxInput!): StashBoxValidationResult!

  # System status
  systemStatus: SystemStatus!

  # Job status
  jobQueue: [Job!]
  findJob(input: FindJobInput!): Job

  dlnaStatus: DLNAStatus!

  # Get everything

  allScenes: [Scene!]! @deprecated(reason: "Use findScenes instead")
  allSceneMarkers: [SceneMarker!]!
    @deprecated(reason: "Use findSceneMarkers instead")
  allImages: [Image!]! @deprecated(reason: "Use findImages instead")
  allGalleries: [Gallery!]! @deprecated(reason: "Use findGalleries instead")

  allPerformers: [Performer!]!
  allTags: [Tag!]! @deprecated(reason: "Use findTags instead")
  allStudios: [Studio!]! @deprecated(reason: "Use findStudios instead")
  allMovies: [Movie!]! @deprecated(reason: "Use findGroups instead")

  users: [User!]! @hasRole(role: ADMIN)
  """
  Returns currently authenticated user
  """
  me: User

  # Version
  version: Version!

  # LatestVersion
  latestversion: LatestVersion!
}

type Mutation {
  setup(input: SetupInput!): Boolean! @hasRole(role: ADMIN)

  "Migrates the schema to the required version. Returns the job ID"
  migrate(input: MigrateInput!): ID! @hasRole(role: ADMIN)

  "Downloads and installs ffmpeg and ffprobe binaries into the configuration directory. Returns the job ID."
  downloadFFMpeg: ID! @hasRole(role: ADMIN)

  sceneCreate(input: SceneCreateInput!): Scene @hasRole(role: MODIFY)
  sceneUpdate(input: SceneUpdateInput!): Scene @hasRole(role: MODIFY)
  sceneMerge(input: SceneMergeInput!): Scene @hasRole(role: MODIFY)
  bulkSceneUpdate(input: BulkSceneUpdateInput!): [Scene!] @hasRole(role: MODIFY)
  sceneDestroy(input: SceneDestroyInput!): Boolean! @hasRole(role: MODIFY)
  scenesDestroy(input: ScenesDestroyInput!): Boolean! @hasRole(role: MODIFY)
  scenesUpdate(input: [SceneUpdateInput!]!): [Scene] @hasRole(role: MODIFY)

  "Increments the o-counter for a scene. Returns the new value"
  sceneIncrementO(id: ID!): Int!
    @deprecated(reason: "Use sceneAddO instead")
    @hasRole(role: MODIFY)
  "Decrements the o-counter for a scene. Returns the new value"
  sceneDecrementO(id: ID!): Int!
    @deprecated(reason: "Use sceneRemoveO instead")
    @hasRole(role: MODIFY)

  "Increments the o-counter for a scene. Uses the current time if none provided."
  sceneAddO(id: ID!, times: [Timestamp!]): HistoryMutationResult!
    @hasRole(role: MODIFY)
  "Decrements the o-counter for a scene, removing the last recorded time if specific time not provided. Returns the new value"
  sceneDeleteO(id: ID!, times: [Timestamp!]): HistoryMutationResult!
    @hasRole(role: MODIFY)

  "Resets the o-counter for a scene to 0. Returns the new value"
  sceneResetO(id: ID!): Int! @hasRole(role: MODIFY)

  "Sets the resume time point (if provided) and adds the provided duration to the scene's play duration"
  sceneSaveActivity(id: ID!, resume_time: Float, playDuration: Float): Boolean!
    @hasRole(role: MODIFY)

  "Resets the resume time point and play duration"
  sceneResetActivity(
    id: ID!
    reset_resume: Boolean
    reset_duration: Boolean
  ): Boolean! @hasRole(role: MODIFY)

  "Increments the play count for the scene. Returns the new play count value."
  sceneIncrementPlayCount(id: ID!): Int!
    @deprecated(reason: "Use sceneAddPlay instead")
    @hasRole(role: MODIFY)

  "Increments the play count for the scene. Uses the current time if none provided."
  sceneAddPlay(id: ID!, times: [Timestamp!]): HistoryMutationResult!
    @hasRole(role: MODIFY)
  "Decrements the play count for the scene, removing the specific times or the last recorded time if not provided."
  sceneDeletePlay(id: ID!, times: [Timestamp!]): HistoryMutationResult!
    @hasRole(role: MODIFY)
  "Resets the play count for a scene to 0. Returns the new play count value."
  sceneResetPlayCount(id: ID!): Int! @hasRole(role: MODIFY)

  "Generates screenshot at specified time in seconds. Leave empty to generate default screenshot"
  sceneGenerateScreenshot(id: ID!, at: Float): String! @hasRole(role: ADMIN)

  sceneMarkerCreate(input: SceneMarkerCreateInput!): SceneMarker
    @hasRole(role: MODIFY)
  sceneMarkerUpdate(input: SceneMarkerUpdateInput!): SceneMarker
    @hasRole(role: MODIFY)
  bulkSceneMarkerUpdate(input: BulkSceneMarkerUpdateInput!): [SceneMarker!]
    @hasRole(role: MODIFY)
  sceneMarkerDestroy(id: ID!): Boolean! @hasRole(role: MODIFY)
  sceneMarkersDestroy(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)

  sceneAssignFile(input: AssignSceneFileInput!): Boolean! @hasRole(role: MODIFY)

  imageUpdate(input: ImageUpdateInput!): Image @hasRole(role: MODIFY)
  bulkImageUpdate(input: BulkImageUpdateInput!): [Image!] @hasRole(role: MODIFY)
  imageDestroy(input: ImageDestroyInput!): Boolean! @hasRole(role: MODIFY)
  imagesDestroy(input: ImagesDestroyInput!): Boolean! @hasRole(role: MODIFY)
  imagesUpdate(input: [ImageUpdateInput!]!): [Image] @hasRole(role: MODIFY)

  "Increments the o-counter for an image. Returns the new value"
  imageIncrementO(id: ID!): Int! @hasRole(role: MODIFY)
  "Decrements the o-counter for an image. Returns the new value"
  imageDecrementO(id: ID!): Int! @hasRole(role: MODIFY)
  "Resets the o-counter for a image to 0. Returns the new value"
  imageResetO(id: ID!): Int! @hasRole(role: MODIFY)

  galleryCreate(input: GalleryCreateInput!): Gallery @hasRole(role: MODIFY)
  galleryUpdate(input: GalleryUpdateInput!): Gallery @hasRole(role: MODIFY)
  bulkGalleryUpdate(input: BulkGalleryUpdateInput!): [Gallery!]
    @hasRole(role: MODIFY)
  galleryDestroy(input: GalleryDestroyInput!): Boolean! @hasRole(role: MODIFY)
  galleriesUpdate(input: [GalleryUpdateInput!]!): [Gallery]
    @hasRole(role: MODIFY)

  addGalleryImages(input: GalleryAddInput!): Boolean! @hasRole(role: MODIFY)
  removeGalleryImages(input: GalleryRemoveInput!): Boolean!
    @hasRole(role: MODIFY)
  setGalleryCover(input: GallerySetCoverInput!): Boolean! @hasRole(role: MODIFY)
  resetGalleryCover(input: GalleryResetCoverInput!): Boolean!
    @hasRole(role: MODIFY)

  galleryChapterCreate(input: GalleryChapterCreateInput!): GalleryChapter
    @hasRole(role: MODIFY)
  galleryChapterUpdate(input: GalleryChapterUpdateInput!): GalleryChapter
    @hasRole(role: MODIFY)
  galleryChapterDestroy(id: ID!): Boolean! @hasRole(role: MODIFY)

  performerCreate(input: PerformerCreateInput!): Performer
    @hasRole(role: MODIFY)
  performerUpdate(input: PerformerUpdateInput!): Performer
    @hasRole(role: MODIFY)
  performerDestroy(input: PerformerDestroyInput!): Boolean!
    @hasRole(role: MODIFY)
  performersDestroy(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)
  bulkPerformerUpdate(input: BulkPerformerUpdateInput!): [Performer!]
    @hasRole(role: MODIFY)
  performerMerge(input: PerformerMergeInput!): Performer! @hasRole(role: MODIFY)

  studioCreate(input: StudioCreateInput!): Studio @hasRole(role: MODIFY)
  studioUpdate(input: StudioUpdateInput!): Studio @hasRole(role: MODIFY)
  studioDestroy(input: StudioDestroyInput!): Boolean! @hasRole(role: MODIFY)
  studiosDestroy(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)
  bulkStudioUpdate(input: BulkStudioUpdateInput!): [Studio!]
    @hasRole(role: MODIFY)

  movieCreate(input: MovieCreateInput!): Movie
    @deprecated(reason: "Use groupCreate instead")
    @hasRole(role: MODIFY)
  movieUpdate(input: MovieUpdateInput!): Movie
    @deprecated(reason: "Use groupUpdate instead")
    @hasRole(role: MODIFY)
  movieDestroy(input: MovieDestroyInput!): Boolean!
    @deprecated(reason: "Use groupDestroy instead")
    @hasRole(role: MODIFY)
  moviesDestroy(ids: [ID!]!): Boolean!
    @deprecated(reason: "Use groupsDestroy instead")
    @hasRole(role: MODIFY)
  bulkMovieUpdate(input: BulkMovieUpdateInput!): [Movie!]
    @deprecated(reason: "Use bulkGroupUpdate instead")
    @hasRole(role: MODIFY)

  groupCreate(input: GroupCreateInput!): Group @hasRole(role: MODIFY)
  groupUpdate(input: GroupUpdateInput!): Group @hasRole(role: MODIFY)
  groupDestroy(input: GroupDestroyInput!): Boolean! @hasRole(role: MODIFY)
  groupsDestroy(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)
  bulkGroupUpdate(input: BulkGroupUpdateInput!): [Group!] @hasRole(role: MODIFY)

  addGroupSubGroups(input: GroupSubGroupAddInput!): Boolean!
    @hasRole(role: MODIFY)
  removeGroupSubGroups(input: GroupSubGroupRemoveInput!): Boolean!
    @hasRole(role: MODIFY)

  "Reorder sub groups within a group. Returns true if successful."
  reorderSubGroups(input: ReorderSubGroupsInput!): Boolean!
    @hasRole(role: MODIFY)

  tagCreate(input: TagCreateInput!): Tag @hasRole(role: MODIFY)
  tagUpdate(input: TagUpdateInput!): Tag @hasRole(role: MODIFY)
  tagDestroy(input: TagDestroyInput!): Boolean! @hasRole(role: MODIFY)
  tagsDestroy(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)
  tagsMerge(input: TagsMergeInput!): Tag @hasRole(role: MODIFY)
  bulkTagUpdate(input: BulkTagUpdateInput!): [Tag!] @hasRole(role: MODIFY)

  """
  Moves the given files to the given destination. Returns true if successful.
  Either the destination_folder or destination_folder_id must be provided.
  If both are provided, the destination_folder_id takes precedence.
  Destination folder must be a subfolder of one of the stash library paths.
  If provided, destination_basename must be a valid filename with an extension that
  matches one of the media extensions.
  Creates folder hierarchy if needed.
  """
  moveFiles(input: MoveFilesInput!): Boolean! @hasRole(role: MODIFY)
  deleteFiles(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)
  "Deletes file entries from the database without deleting the files from the filesystem"
  destroyFiles(ids: [ID!]!): Boolean! @hasRole(role: MODIFY)

  fileSetFingerprints(input: FileSetFingerprintsInput!): Boolean!
  "Reveal the file in the system file manager"
  revealFileInFileManager(id: ID!): Boolean!
  "Reveal the folder in the system file manager"
  revealFolderInFileManager(id: ID!): Boolean!

  # Saved filters
  saveFilter(input: SaveFilterInput!): SavedFilter! @hasRole(role: MODIFY)
  destroySavedFilter(input: DestroyFilterInput!): Boolean!
    @hasRole(role: MODIFY)
  setDefaultFilter(input: SetDefaultFilterInput!): Boolean!
    @deprecated(reason: "now uses UI config")
    @hasRole(role: MODIFY)

  "Change general configuration options"
  configureGeneral(input: ConfigGeneralInput!): ConfigGeneralResult!
    @hasRole(role: ADMIN)
  configureInterface(input: ConfigInterfaceInput!): ConfigInterfaceResult!
    @hasRole(role: ADMIN)
  configureDLNA(input: ConfigDLNAInput!): ConfigDLNAResult!
    @hasRole(role: ADMIN)
  configureScraping(input: ConfigScrapingInput!): ConfigScrapingResult!
    @hasRole(role: ADMIN)
  configureDefaults(
    input: ConfigDefaultSettingsInput!
  ): ConfigDefaultSettingsResult! @hasRole(role: ADMIN)

  "overwrites the entire plugin configuration for the given plugin"
  configurePlugin(plugin_id: ID!, input: Map!): Map! @hasRole(role: ADMIN)

  """
  overwrites the UI configuration
  if input is provided, then the entire UI configuration is replaced
  if partial is provided, then the partial UI configuration is merged into the existing UI configuration
  """
  configureUI(input: Map, partial: Map): Map! @hasRole(role: ADMIN)
  """
  sets a single UI key value
  key is a dot separated path to the value
  """
  configureUISetting(key: String!, value: Any): Map! @hasRole(role: ADMIN)

  "Generate and set (or clear) API key for the current user"
  generateAPIKey(input: GenerateAPIKeyInput!): String! @hasRole(role: GENERATE_API_KEY)

  generateUserAPIKey(username: String!, input: GenerateAPIKeyInput!): String!
    @hasRole(role: ADMIN)

  "Returns a link to download the result"
  exportObjects(input: ExportObjectsInput!): String @hasRole(role: ADMIN)

  "Performs an incremental import. Returns the job ID"
  importObjects(input: ImportObjectsInput!): ID! @hasRole(role: ADMIN)

  "Start an full import. Completely wipes the database and imports from the metadata directory. Returns the job ID"
  metadataImport: ID! @hasRole(role: ADMIN)
  "Start a full export. Outputs to the metadata directory. Returns the job ID"
  metadataExport: ID! @hasRole(role: ADMIN)
  "Start a scan. Returns the job ID"
  metadataScan(input: ScanMetadataInput!): ID! @hasRole(role: ADMIN)
  "Start generating content. Returns the job ID"
  metadataGenerate(input: GenerateMetadataInput!): ID! @hasRole(role: ADMIN)
  "Start auto-tagging. Returns the job ID"
  metadataAutoTag(input: AutoTagMetadataInput!): ID! @hasRole(role: ADMIN)
  "Clean metadata. Returns the job ID"
  metadataClean(input: CleanMetadataInput!): ID! @hasRole(role: ADMIN)
  "Clean generated files. Returns the job ID"
  metadataCleanGenerated(input: CleanGeneratedInput!): ID! @hasRole(role: ADMIN)
  "Identifies scenes using scrapers. Returns the job ID"
  metadataIdentify(input: IdentifyMetadataInput!): ID! @hasRole(role: ADMIN)

  "Migrate generated files for the current hash naming"
  migrateHashNaming: ID! @hasRole(role: ADMIN)
  "Migrates legacy scene screenshot files into the blob storage"
  migrateSceneScreenshots(input: MigrateSceneScreenshotsInput!): ID!
    @hasRole(role: ADMIN)
  "Migrates blobs from the old storage system to the current one"
  migrateBlobs(input: MigrateBlobsInput!): ID! @hasRole(role: ADMIN)

  "Anonymise the database in a separate file. Optionally returns a link to download the database file"
  anonymiseDatabase(input: AnonymiseDatabaseInput!): String
    @hasRole(role: ADMIN)

  "Optimises the database. Returns the job ID"
  optimiseDatabase: ID! @hasRole(role: ADMIN)

  "Reload scrapers"
  reloadScrapers: Boolean! @hasRole(role: ADMIN)

  """
  Enable/disable plugins - enabledMap is a map of plugin IDs to enabled booleans.
  Plugins not in the map are not affected.
  """
  setPluginsEnabled(enabledMap: BoolMap!): Boolean! @hasRole(role: ADMIN)

  """
  Run a plugin task.
  If task_name is provided, then the task must exist in the plugin config and the tasks configuration
  will be used to run the plugin.
  If no task_name is provided, then the plugin will be executed with the arguments provided only.
  Returns the job ID
  """
  runPluginTask(
    plugin_id: ID!
    "if provided, then the default args will be applied"
    task_name: String
    "displayed in the task queue"
    description: String
    args: [PluginArgInput!] @deprecated(reason: "Use args_map instead")
    args_map: Map
  ): ID! @hasRole(role: MODIFY)

  """
  Runs a plugin operation. The operation is run immediately and does not use the job queue.
  Returns a map of the result.
  """
  runPluginOperation(plugin_id: ID!, args: Map): Any @hasRole(role: MODIFY)

  reloadPlugins: Boolean! @hasRole(role: ADMIN)

  """
  Installs the given packages.
  If a package is already installed, it will be updated if needed..
  If an error occurs when installing a package, the job will continue to install the remaining packages.
  Returns the job ID
  """
  installPackages(type: PackageType!, packages: [PackageSpecInput!]!): ID!
    @hasRole(role: ADMIN)
  """
  Updates the given packages.
  If a package is not installed, it will not be installed.
  If a package does not need to be updated, it will not be updated.
  If no packages are provided, all packages of the given type will be updated.
  If an error occurs when updating a package, the job will continue to update the remaining packages.
  Returns the job ID.
  """
  updatePackages(type: PackageType!, packages: [PackageSpecInput!]): ID!
    @hasRole(role: ADMIN)
  """
  Uninstalls the given packages.
  If an error occurs when uninstalling a package, the job will continue to uninstall the remaining packages.
  Returns the job ID
  """
  uninstallPackages(type: PackageType!, packages: [PackageSpecInput!]!): ID!
    @hasRole(role: ADMIN)

  stopJob(job_id: ID!): Boolean! @hasRole(role: ADMIN)
  stopAllJobs: Boolean! @hasRole(role: ADMIN)

  "Submit fingerprints to stash-box instance"
  submitStashBoxFingerprints(
    input: StashBoxFingerprintSubmissionInput!
  ): Boolean! @hasRole(role: MODIFY)

  "Submit scene as draft to stash-box instance"
  submitStashBoxSceneDraft(input: StashBoxDraftSubmissionInput!): ID
    @hasRole(role: MODIFY)
  "Submit performer as draft to stash-box instance"
  submitStashBoxPerformerDraft(input: StashBoxDraftSubmissionInput!): ID
    @hasRole(role: MODIFY)

  "Backup the database. Optionally returns a link to download the database file"
  backupDatabase(input: BackupDatabaseInput!): String @hasRole(role: ADMIN)

  "DANGEROUS: Execute an arbitrary SQL statement that returns rows."
  querySQL(sql: String!, args: [Any]): SQLQueryResult! @hasRole(role: ADMIN)

  "DANGEROUS: Execute an arbitrary SQL statement without returning any rows."
  execSQL(sql: String!, args: [Any]): SQLExecResult! @hasRole(role: ADMIN)

  "Run batch performer tag task. Returns the job ID."
  stashBoxBatchPerformerTag(input: StashBoxBatchTagInput!): String!
    @hasRole(role: ADMIN)
  "Run batch studio tag task. Returns the job ID."
  stashBoxBatchStudioTag(input: StashBoxBatchTagInput!): String!
    @hasRole(role: ADMIN)
  "Run batch tag tag task. Returns the job ID."
  stashBoxBatchTagTag(input: StashBoxBatchTagInput!): String! @hasRole(role: ADMIN)

  "Enables DLNA for an optional duration. Has no effect if DLNA is enabled by default"
  enableDLNA(input: EnableDLNAInput!): Boolean! @hasRole(role: ADMIN)
  "Disables DLNA for an optional duration. Has no effect if DLNA is disabled by default"
  disableDLNA(input: DisableDLNAInput!): Boolean! @hasRole(role: ADMIN)
  "Enables an IP address for DLNA for an optional duration"
  addTempDLNAIP(input: AddTempDLNAIPInput!): Boolean! @hasRole(role: ADMIN)
  "Removes an IP address from the temporary DLNA whitelist"
  removeTempDLNAIP(input: RemoveTempDLNAIPInput!): Boolean!
    @hasRole(role: ADMIN)

  userCreate(input: UserCreateInput!): User @hasRole(role: ADMIN)
  userUpdate(input: UserUpdateInput!): User @hasRole(role: ADMIN)
  userDestroy(input: UserDestroyInput!): Boolean! @hasRole(role: ADMIN)
  changeUserPassword(input: ChangeUserPasswordInput!): Boolean!
    @hasRole(role: ADMIN)
  changePassword(input: UserChangePasswordInput!): Boolean!
}

type Subscription {
  "Update from the metadata manager"
  jobsSubscribe: JobStatusUpdate!

  loggingSubscribe: [LogEntry!]!

  scanCompleteSubscribe: Boolean!
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
