// Code generated by mockery v2.21.6. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/stashapp/stash/pkg/group"

	mock "github.com/stretchr/testify/mock"

	models "github.com/stashapp/stash/pkg/models"
)

// GroupService is an autogenerated mock type for the GroupService type
type GroupService struct {
	mock.Mock
}

// AddSubGroups provides a mock function with given fields: ctx, groupID, subGroups, insertIndex
func (_m *GroupService) AddSubGroups(ctx context.Context, groupID int, subGroups []models.GroupIDDescription, insertIndex *int) error {
	ret := _m.Called(ctx, groupID, subGroups, insertIndex)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []models.GroupIDDescription, *int) error); ok {
		r0 = rf(ctx, groupID, subGroups, insertIndex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, input
func (_m *GroupService) Create(ctx context.Context, input *models.CreateGroupInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateGroupInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveSubGroups provides a mock function with given fields: ctx, groupID, subGroupIDs
func (_m *GroupService) RemoveSubGroups(ctx context.Context, groupID int, subGroupIDs []int) error {
	ret := _m.Called(ctx, groupID, subGroupIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, groupID, subGroupIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReorderSubGroups provides a mock function with given fields: ctx, groupID, subGroupIDs, insertPointID, insertAfter
func (_m *GroupService) ReorderSubGroups(ctx context.Context, groupID int, subGroupIDs []int, insertPointID int, insertAfter bool) error {
	ret := _m.Called(ctx, groupID, subGroupIDs, insertPointID, insertAfter)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int, int, bool) error); ok {
		r0 = rf(ctx, groupID, subGroupIDs, insertPointID, insertAfter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartial provides a mock function with given fields: ctx, id, updatedGroup, frontImage, backImage
func (_m *GroupService) UpdatePartial(ctx context.Context, id int, updatedGroup models.GroupPartial, frontImage group.ImageInput, backImage group.ImageInput) (*models.Group, error) {
	ret := _m.Called(ctx, id, updatedGroup, frontImage, backImage)

	var r0 *models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.GroupPartial, group.ImageInput, group.ImageInput) (*models.Group, error)); ok {
		return rf(ctx, id, updatedGroup, frontImage, backImage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.GroupPartial, group.ImageInput, group.ImageInput) *models.Group); ok {
		r0 = rf(ctx, id, updatedGroup, frontImage, backImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.GroupPartial, group.ImageInput, group.ImageInput) error); ok {
		r1 = rf(ctx, id, updatedGroup, frontImage, backImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGroupService interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupService creates a new instance of GroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupService(t mockConstructorTestingTNewGroupService) *GroupService {
	mock := &GroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
