// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileJoinReaderWriter is an autogenerated mock type for the FileJoinReaderWriter type
type FileJoinReaderWriter struct {
	mock.Mock
}

// GetFileIDs provides a mock function with given fields: id
func (_m *FileJoinReaderWriter) GetFileIDs(id int) ([]int, error) {
	ret := _m.Called(id)

	var r0 []int
	if rf, ok := ret.Get(0).(func(int) []int); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFiles provides a mock function with given fields: id, fileIDs
func (_m *FileJoinReaderWriter) UpdateFiles(id int, fileIDs []int) error {
	ret := _m.Called(id, fileIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []int) error); ok {
		r0 = rf(id, fileIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
