// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// PerformerReaderWriter is an autogenerated mock type for the PerformerReaderWriter type
type PerformerReaderWriter struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *PerformerReaderWriter) All() ([]*models.Performer, error) {
	ret := _m.Called()

	var r0 []*models.Performer
	if rf, ok := ret.Get(0).(func() []*models.Performer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: newPerformer
func (_m *PerformerReaderWriter) Create(newPerformer models.Performer) (*models.Performer, error) {
	ret := _m.Called(newPerformer)

	var r0 *models.Performer
	if rf, ok := ret.Get(0).(func(models.Performer) *models.Performer); ok {
		r0 = rf(newPerformer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Performer) error); ok {
		r1 = rf(newPerformer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNames provides a mock function with given fields: names, nocase
func (_m *PerformerReaderWriter) FindByNames(names []string, nocase bool) ([]*models.Performer, error) {
	ret := _m.Called(names, nocase)

	var r0 []*models.Performer
	if rf, ok := ret.Get(0).(func([]string, bool) []*models.Performer); ok {
		r0 = rf(names, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, bool) error); ok {
		r1 = rf(names, nocase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySceneID provides a mock function with given fields: sceneID
func (_m *PerformerReaderWriter) FindBySceneID(sceneID int) ([]*models.Performer, error) {
	ret := _m.Called(sceneID)

	var r0 []*models.Performer
	if rf, ok := ret.Get(0).(func(int) []*models.Performer); ok {
		r0 = rf(sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ids
func (_m *PerformerReaderWriter) FindMany(ids []int) ([]*models.Performer, error) {
	ret := _m.Called(ids)

	var r0 []*models.Performer
	if rf, ok := ret.Get(0).(func([]int) []*models.Performer); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNamesBySceneID provides a mock function with given fields: sceneID
func (_m *PerformerReaderWriter) FindNamesBySceneID(sceneID int) ([]*models.Performer, error) {
	ret := _m.Called(sceneID)

	var r0 []*models.Performer
	if rf, ok := ret.Get(0).(func(int) []*models.Performer); ok {
		r0 = rf(sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerformerImage provides a mock function with given fields: performerID
func (_m *PerformerReaderWriter) GetPerformerImage(performerID int) ([]byte, error) {
	ret := _m.Called(performerID)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(performerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: updatedPerformer
func (_m *PerformerReaderWriter) Update(updatedPerformer models.Performer) (*models.Performer, error) {
	ret := _m.Called(updatedPerformer)

	var r0 *models.Performer
	if rf, ok := ret.Get(0).(func(models.Performer) *models.Performer); ok {
		r0 = rf(updatedPerformer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Performer) error); ok {
		r1 = rf(updatedPerformer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePerformerImage provides a mock function with given fields: performerID, image
func (_m *PerformerReaderWriter) UpdatePerformerImage(performerID int, image []byte) error {
	ret := _m.Called(performerID, image)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(performerID, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
