name: Build

on:
  push:
    branches: [ develop, master, github-actions ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout
      run: git fetch --prune --unshallow --tags

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Pre-install
      run: make pre-ui

    - name: Generate
      run: make generate
    
    - name: Validate
      run: make ui-validate fmt-check vet it

    - name: Build UI
      run: make ui-only

    - name: Cross Compile
      run: |
        docker pull stashapp/compiler:4
        ./scripts/cross-compile.sh
    
    - name: Generate checksums
      run: |
        git describe --tags --exclude latest_develop | tee CHECKSUMS_SHA1
        sha1sum dist/stash-* | sed 's/dist\///g' | tee -a CHECKSUMS_SHA1
    
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          dist/stash-osx
          dist/stash-win
          dist/stash-linux

    # TODO - set RELEASE_DATE and STASH_VERSION
    # TODO - make dev release
    # TODO - make master release
    # TODO - push docker images
