# TODO(audio): update this file

type AudioFileType {
  size: String
  duration: Float
  audio_codec: String
  samplerate: Float
  bitrate: Int
}

type AudioPathsType {
  screenshot: String # Resolver
  preview: String # Resolver
  stream: String # Resolver
  webp: String # Resolver
  vtt: String # Resolver
  sprite: String # Resolver
  funscript: String # Resolver
  caption: String # Resolver
}

type AudioGroup {
  group: Group!
  audio_index: Int
}

# TODO(audio|AudioCaption): need to update IF AudioCaption required
# type AudioCaption {
#   language_code: String!
#   caption_type: String!
# }

type Audio {
  id: ID!
  title: String
  code: String
  details: String
  url: String @deprecated(reason: "Use urls")
  urls: [String!]!
  date: String
  # rating expressed as 1-100
  rating100: Int
  organized: Boolean!
  o_counter: Int
  # TODO(audio|AudioCaption): need to update IF AudioCaption required
  # captions: [AudioCaption!]
  captions: [VideoCaption!]
  created_at: Time!
  updated_at: Time!
  "The last time play count was updated"
  last_played_at: Time
  "The time index a audio was left at"
  resume_time: Float
  "The total time a audio has spent playing"
  play_duration: Float
  "The number ot times a audio has been played"
  play_count: Int

  "Times a audio was played"
  play_history: [Time!]!
  "Times the o counter was incremented"
  o_history: [Time!]!

  files: [AudioFile!]!
  paths: AudioPathsType! # Resolver
  # TODO(future|audio_markers): add in audio markers
  #  audio_markers: [AudioMarker!]!
  studio: Studio
  groups: [AudioGroup!]!
  tags: [Tag!]!
  performers: [Performer!]!

  custom_fields: Map!

  "Return valid stream paths"
  audioStreams: [AudioStreamEndpoint!]!
}

input AudioGroupInput {
  group_id: ID!
  audio_index: Int
}

input AudioCreateInput {
  title: String
  code: String
  details: String
  url: String @deprecated(reason: "Use urls")
  urls: [String!]
  date: String
  # rating expressed as 1-100
  rating100: Int
  organized: Boolean
  studio_id: ID
  performer_ids: [ID!]
  groups: [AudioGroupInput!]
  tag_ids: [ID!]
  "This should be a URL or a base64 encoded data URL"
  cover_image: String

  """
  The first id will be assigned as primary.
  Files will be reassigned from existing audios if applicable.
  Files must not already be primary for another audio.
  """
  file_ids: [ID!]

  custom_fields: Map
}

input AudioUpdateInput {
  clientMutationId: String
  id: ID!
  title: String
  code: String
  details: String
  url: String @deprecated(reason: "Use urls")
  urls: [String!]
  date: String
  # rating expressed as 1-100
  rating100: Int
  o_counter: Int
    @deprecated(reason: "Unsupported - Use audioIncrementO/audioDecrementO")
  organized: Boolean
  studio_id: ID
  performer_ids: [ID!]
  groups: [AudioGroupInput!]
  tag_ids: [ID!]
  "This should be a URL or a base64 encoded data URL"
  cover_image: String

  "The time index a audio was left at"
  resume_time: Float
  "The total time a audio has spent playing"
  play_duration: Float
  "The number ot times a audio has been played"
  play_count: Int
    @deprecated(
      reason: "Unsupported - Use audioIncrementPlayCount/audioDecrementPlayCount"
    )

  primary_file_id: ID

  custom_fields: CustomFieldsInput
}

input BulkAudioUpdateInput {
  clientMutationId: String
  ids: [ID!]
  title: String
  code: String
  details: String
  url: String @deprecated(reason: "Use urls")
  urls: BulkUpdateStrings
  date: String
  # rating expressed as 1-100
  rating100: Int
  organized: Boolean
  studio_id: ID
  performer_ids: BulkUpdateIds
  tag_ids: BulkUpdateIds
  group_ids: BulkUpdateIds

  custom_fields: CustomFieldsInput
}

input AudioDestroyInput {
  id: ID!
  delete_file: Boolean
  delete_generated: Boolean
  "If true, delete the file entry from the database if the file is not assigned to any other objects"
  destroy_file_entry: Boolean
}

input AudiosDestroyInput {
  ids: [ID!]!
  delete_file: Boolean
  delete_generated: Boolean
  "If true, delete the file entry from the database if the file is not assigned to any other objects"
  destroy_file_entry: Boolean
}

type FindAudiosResultType {
  count: Int!
  "Total duration in seconds"
  duration: Float!
  "Total file size in bytes"
  filesize: Float!
  audios: [Audio!]!
}

input AudioParserInput {
  ignoreWords: [String!]
  whitespaceCharacters: String
  capitalizeTitle: Boolean
  ignoreOrganized: Boolean
}

type AudioParserResult {
  audio: Audio!
  title: String
  code: String
  details: String
  url: String
  date: String
  # rating expressed as 1-100
  rating100: Int
  studio_id: ID
  performer_ids: [ID!]
  tag_ids: [ID!]
}

type AudioParserResultType {
  count: Int!
  results: [AudioParserResult!]!
}

input AudioHashInput {
  checksum: String
  oshash: String
}

type AudioStreamEndpoint {
  url: String!
  mime_type: String
  label: String
}

input AssignAudioFileInput {
  audio_id: ID!
  file_id: ID!
}

input AudioMergeInput {
  """
  If destination audio has no files, then the primary file of the
  first source audio will be assigned as primary
  """
  source: [ID!]!
  destination: ID!
  # values defined here will override values in the destination
  values: AudioUpdateInput

  # if true, the source history will be combined with the destination
  play_history: Boolean
  o_history: Boolean
}
