enum RoleEnum {
  ADMIN
  READ
  MODIFY
}

directive @hasRole(role: RoleEnum!) on FIELD_DEFINITION
directive @isUserOwner on FIELD_DEFINITION

type User {
  name: String!
  """
  If the user has no roles, they are considered locked and cannot log in.
  Should not be visible to other users
  """
  roles: [RoleEnum!] @isUserOwner
  """Should not be visible to other users"""
  api_key: String @isUserOwner
}

input UserCreateInput {
  name: String!
  """Password in plain text"""
  password: String!
  roles: [RoleEnum!]!
}

input UserUpdateInput {
  existingName: String!
  name: String!
  roles: [RoleEnum!]!
}

input UserDestroyInput {
    name: String!
}

input UserChangePasswordInput {
  """Password in plain text"""
  existingPassword: String!
  newPassword: String!
}

input ChangeUserPasswordInput {
  name: String!
  newPassword: String!
}